# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rotblock < Formula
  desc "Shield distracting iPhone apps while your AI coding agent is working"
  homepage "https://github.com/JordaoGustavo/homebrew-rotblock"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.0/rotblock_0.1.0_darwin_amd64.tar.gz"
      sha256 "45a82a79d40f30ce516f3ac9d59c2a904aaf5622326549998525e1794378c5e6"

      define_method(:install) do
        bin.install "rotblock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.0/rotblock_0.1.0_darwin_arm64.tar.gz"
      sha256 "3a1c1a23a6a3a46d052417ded9c69ac6b95e8aceda5ea6624e4c4165f7ac374d"

      define_method(:install) do
        bin.install "rotblock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.0/rotblock_0.1.0_linux_amd64.tar.gz"
      sha256 "cee31c9231080b59b2f671ef8a055a7b60e4f099869168193bfdd442d8419fd9"
      define_method(:install) do
        bin.install "rotblock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.0/rotblock_0.1.0_linux_arm64.tar.gz"
      sha256 "5e9502ec1e04a4826937fed5e046ca7d5802ffaab09319ec4f89c17ab725e938"
      define_method(:install) do
        bin.install "rotblock"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rotblock --version")
  end
end
