# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rotblock < Formula
  desc "Shield distracting iPhone apps while your AI coding agent is working"
  homepage "https://github.com/JordaoGustavo/homebrew-rotblock"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.2/rotblock_0.1.2_darwin_amd64.tar.gz"
      sha256 "e4f1ebb130a8158748282b6016dc8385f4866c8d4fc9f881d0ba13ebda953f9d"

      define_method(:install) do
        bin.install "rotblock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.2/rotblock_0.1.2_darwin_arm64.tar.gz"
      sha256 "81a7329b9ad0b98326ca07bbedf1579672f1d217e3a5cf0c9642c66519a48611"

      define_method(:install) do
        bin.install "rotblock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.2/rotblock_0.1.2_linux_amd64.tar.gz"
      sha256 "0b38aab2f616a50d8d3fa3fa4b602bbaccfd50492255dd720431084ecf2f82d5"
      define_method(:install) do
        bin.install "rotblock"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/JordaoGustavo/homebrew-rotblock/releases/download/v0.1.2/rotblock_0.1.2_linux_arm64.tar.gz"
      sha256 "acb9e5caa26075a56ad71d1c07516036c53608a6b82c3854f2a31c05a7a3826d"
      define_method(:install) do
        bin.install "rotblock"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/rotblock --version")
  end
end
